language: ruby
sudo: false
cache: bundler
branches:
  only: master
before_install:
  - gem update --system
  - gem update bundler
script: bundle exec rake $TASK
env:
- TASK=test
- TASK=rubocop
rvm:
  - 2.3
  - 2.4
  - 2.5
